import { Component,useEffect,useLayoutEffect,useMemo,useRef } from 'react';
import type { ReactNode } from 'react';
import { Canvas,useFrame,useThree } from '@react-three/fiber';
import { Color,InstancedMesh,Object3D } from 'three';
import type { LabState } from '../content/types';
interface Props {mode:'field'|'pixel';state:LabState;active:boolean;reduced:boolean;onLost:()=>void}
function Architecture({state}:{state:LabState}){return <><ambientLight intensity={.55}/><hemisphereLight args={['#d8e1e8','#16171a',1.15]}/><directionalLight position={[(state.position[0]-.5)*16,2.2+(1-state.position[1])*7,4]} intensity={1.5+state.intensity*.065} color={state.color} castShadow shadow-mapSize={[1024,1024]} shadow-camera-left={-8} shadow-camera-right={8} shadow-camera-top={8} shadow-camera-bottom={-8} shadow-bias={-.001} shadow-normalBias={.02}/><pointLight position={[-4,4,5]} intensity={18} distance={18} color="#84a9b8"/><group position={[0,0,0]}>{Array.from({length:6},(_,i)=><mesh key={i} castShadow receiveShadow position={[-3+i*1.2,1.55,0]}><boxGeometry args={[.16,3.1,3.2]}/><meshStandardMaterial color="#b0aba0" roughness={.86}/></mesh>)}<mesh position={[.1,3.18,-.25]} castShadow receiveShadow><boxGeometry args={[7.2,.16,3.7]}/><meshStandardMaterial color="#a29d93" roughness={.9}/></mesh></group><mesh rotation={[-Math.PI/2,0,0]} receiveShadow position={[0,-.02,0]}><planeGeometry args={[100,100]}/><meshStandardMaterial color="#292a29" roughness={.55} metalness={.13}/></mesh></>;}
function PixelFacade({state,reduced}:{state:LabState;reduced:boolean}){const ref=useRef<InstancedMesh>(null);const timer=useRef(0);const scratch=useMemo(()=>({o:new Object3D(),c:new Color()}),[]);const paint=(time:number)=>{if(!ref.current)return;for(let i=0;i<576;i++){const x=i%32,y=Math.floor(i/32);let a=1,h=.1;if(state.pattern==='wave'){a=.18+.82*(Math.sin(x*.32+y*.22-time*1.4)+1)/2;h=.1+.45*(Math.sin(x*.12-time*.35)+1)/2;}if(state.pattern==='gradient'){a=.4+.6*y/18;h=(x/42+time*.03)%1;}if(state.pattern==='pulse'){a=.2+.8*(Math.sin(time*1.4-Math.hypot(x-16,y-9)*.35)+1)/2;h=.1+.4*a;}scratch.c.setHSL(h,.45,(.05+.45*a)*state.intensity/100);ref.current.setColorAt(i,scratch.c);}if(ref.current.instanceColor)ref.current.instanceColor.needsUpdate=true;};useLayoutEffect(()=>{for(let i=0;i<576;i++){scratch.o.position.set((i%32-15.5)*.28,(Math.floor(i/32)-8.5)*.28+2.8,.06);scratch.o.updateMatrix();ref.current?.setMatrixAt(i,scratch.o.matrix);}if(ref.current)ref.current.instanceMatrix.needsUpdate=true;paint(0);},[]);useEffect(()=>paint(timer.current),[state,reduced]);useFrame((_,delta)=>{if(!state.paused&&!reduced)timer.current+=Math.min(delta,.05)*state.speed/50;paint(timer.current);});return <><ambientLight intensity={.5}/><mesh position={[0,2.8,-.04]}><boxGeometry args={[9.4,5.4,.18]}/><meshStandardMaterial color="#171b21" roughness={.8}/></mesh><instancedMesh ref={ref} args={[undefined,undefined,576]}><circleGeometry args={[.068,12]}/><meshBasicMaterial toneMapped={false}/></instancedMesh><mesh rotation={[-Math.PI/2,0,0]} position={[0,-.05,0]}><planeGeometry args={[60,60]}/><meshStandardMaterial color="#111318"/></mesh></>;}
function Camera({mode,state,onLost}:{mode:string;state:LabState;onLost:()=>void}){const {camera,invalidate,gl}=useThree();useEffect(()=>{if(mode==='field'){camera.position.set(8,5,8);camera.lookAt(0,1.3,0);}else{camera.position.set(6.2,5,12);camera.lookAt(0,2.6,0);}camera.updateProjectionMatrix();invalidate();},[mode,camera,invalidate]);useEffect(()=>{invalidate();},[state,invalidate]);useEffect(()=>{const lost=(e:Event)=>{e.preventDefault();onLost();};gl.domElement.addEventListener('webglcontextlost',lost);return()=>gl.domElement.removeEventListener('webglcontextlost',lost);},[gl,onLost]);return null;}
class Boundary extends Component<{children:ReactNode;onLost:()=>void},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return {failed:true};}componentDidCatch(){this.props.onLost();}render(){return this.state.failed?null:this.props.children;}}
export default function LightScene({mode,state,active,reduced,onLost}:Props){return <Boundary onLost={onLost}><Canvas shadows frameloop={!active?'never':mode==='pixel'&&!state.paused&&!reduced?'always':'demand'} camera={{position:[8,5,8],fov:42,near:.1,far:120}} dpr={[1,1.5]} gl={{antialias:true}}><color attach="background" args={['#0e1216']}/><fog attach="fog" args={['#0e1216',17,50]}/><Camera mode={mode} state={state} onLost={onLost}/>{mode==='field'?<Architecture state={state}/>:<PixelFacade state={state} reduced={reduced}/>}</Canvas></Boundary>;}
