import { useLanguage } from '../../language';

const english: Record<string, string> = {
  '图片建筑光影测试': 'Photo architectural lighting test', '固定视角的建筑图片预览': 'Fixed-view architectural photo preview',
  '正在加载固定视角图片…': 'Loading the fixed-view photo…', '固定视角 · 图片光影测试': 'FIXED VIEW · PHOTO LIGHT LAB',
  '原图暖色灯光': 'Original warm lighting', '在建筑显示区拖动吸引 · 右键推散': 'Drag on the facade to attract · Right-click to scatter',
  '固定视角 · 显示区拖动吸引 · 右键推散': 'Fixed view · Drag to attract · Right-click to scatter',
  '素材在建筑光影模拟与测试项中共享；只在当前浏览器处理，不会上传到服务器。': 'Media is shared between Lightform Studio and Photo Lab. Files stay in this browser and are never uploaded.',
  '图片场景加载失败，请重试。': 'The photo scene failed to load. Please retry.',
  '图片渲染已中断，请重新打开测试项。': 'Photo rendering was interrupted. Reopen Photo Lab to retry.',
  '媒体加载超时，请重试。': 'Media loading timed out. Please retry.',
  '街区塔楼灯带演示': 'Street tower strip demo', '球形展馆地球夜景': 'Earth at night',
  '画面沿塔楼竖向灯带连续显示': 'Image displayed continuously along the vertical strips',
  '塔楼灯带': 'Tower strips', '灯带亮度': 'Strip brightness', '灯带间隙': 'Strip gap', '灯带柔光': 'Strip glow',
  '竖向灯带沿原塔楼轮廓连续显示画面；调节间隙控制灯带宽度。': 'Vertical strips follow the original tower outline. Adjust the gap to change strip width.',
  '街区塔楼点阵演示': 'Street tower dot demo', '弧形展馆点阵演示': 'Curved pavilion dot demo',
  '球形展馆点阵演示': 'Dome pavilion dot demo',
  '场景加载失败。': 'Scene failed to load.', '媒体加载失败。': 'Media failed to load.',
  '请选择 JPG、PNG、WebP、MP4 或 WebM 文件。视频还需由当前浏览器支持解码。': 'Choose a JPG, PNG, WebP, MP4, or WebM file. Video decoding depends on your browser.',
  '演示素材恢复失败。': 'Could not restore the demo media.',
  '无法启动 WebGL，请启用硬件加速或使用支持 WebGL 的浏览器。': 'WebGL could not start. Enable hardware acceleration or use a browser with WebGL support.',
  '重试': 'Retry', '浏览器无法解码此视频。': 'The browser could not decode this video.',
  '视频没有有效的画面尺寸。': 'The video has no valid dimensions.',
  '文件没有有效的画面尺寸。': 'The file has no valid dimensions.',
  '上传已被新的文件替代。': 'Upload replaced by a newer file.',
  '街区塔楼场景加载失败，请重试。': 'The street tower scene failed to load. Please retry.',
  '弧形点阵展馆模型缺少 MEDIA_REFLECTION 网格。': 'The curved pavilion model is missing the MEDIA_REFLECTION mesh.',
  '视频无法播放，请尝试使用浏览器支持的 MP4 或 WebM 编码。': 'Video could not play. Try a browser supported MP4 or WebM encoding.',
  '平滑画面': 'Smooth image', '细密灯珠': 'Fine LEDs', '明显灯珠与暗缝': 'Distinct LEDs and dark gaps',
  'Lightform Studio LED 建筑模拟器': 'Lightform Studio architectural LED simulator',
  '可旋转的 888 Collins 大楼 3D 预览': 'Rotatable 3D preview of 888 Collins',
  '可旋转的弧形展馆 3D 预览': 'Rotatable 3D preview of the curved pavilion',
  '可旋转的球形展馆 3D 预览': 'Rotatable 3D preview of the dome pavilion',
  '正在加载街区塔楼场景…': 'Loading street tower scene…', '选择场景': 'Choose a scene',
  '球形展馆': 'Dome pavilion', '弧形点阵展馆': 'Curved dot pavilion', '弧形展馆': 'Curved pavilion',
  '导出画面': 'Export image', '隐藏素材面板': 'Hide media panel',
  '显示素材面板': 'Show media panel', '素材': 'Media',
  '隐藏参数面板': 'Hide settings panel', '显示参数面板': 'Show settings panel',
  '参数': 'Settings', '素材与播放': 'Media and playback', '内容素材': 'Media',
  '关闭素材面板': 'Close media panel', '关闭错误': 'Dismiss error',
  '上传媒体': 'Upload media', '正在处理媒体…': 'Processing media…',
  '上传图片或视频': 'Upload image or video', '点击选择，或将文件拖拽到此处': 'Click to choose or drop a file here',
  '当前内容': 'Current media', '当前素材预览': 'Media preview',
  '当前视频缩略图': 'Video thumbnail', '恢复演示素材': 'Restore demo media',
  '恢复三个场景的演示素材': 'Restore demos for all three scenes',
  '建筑点阵 · 动态演示': 'Architectural dots · animated demo',
  '暂停视频': 'Pause video', '播放视频': 'Play video', '视频进度': 'Video timeline',
  '画面按塔楼点阵位置采样': 'Image sampled across the tower dots',
  '画面按圆形光点位置采样': 'Image sampled across the dot facade',
  '图片已映射到球形展馆': 'Image mapped onto the dome pavilion',
  '素材只在当前浏览器处理，不会上传到服务器。': 'Media is processed in this browser and is not uploaded.',
  '当前素材供三个场景共用；只在当前浏览器处理，不会上传到服务器。': 'The current media is shared by all three scenes. It stays in this browser and is not uploaded.',
  '显示与视角参数': 'Display and camera settings', '显示参数': 'Display settings',
  '关闭参数面板': 'Close settings panel', '塔楼点阵': 'Tower dots',
  '球形展馆显示': 'Dome display',
  '光点亮度': 'Dot brightness', '整体亮度': 'Brightness',
  '光点间隙': 'Dot gap', '点阵柔光': 'Dot glow', '光点大小': 'Dot size',
  '灯珠颗粒感': 'LED texture', '画面水平位置': 'Horizontal position',
  '画面垂直位置': 'Vertical position', '恢复默认显示': 'Restore defaults',
  '视角预设': 'Camera presets', '街角': 'Street corner', '正面': 'Front',
  '侧面': 'Side', '俯视': 'Above', '重置视角': 'Reset camera',
  '0 平滑画面 · 100 清晰可见的独立灯珠': '0 smooth image · 100 distinct LEDs',
  '街区塔楼两面点阵连续显示画面；调节间隙控制光点大小。': 'The tower dots wrap both street-facing sides. Adjust the gap to change dot size.',
  '圆形光点沿展馆曲面连续采样；暗缝保留原建筑质感。': 'Circular dots sample continuously across the pavilion facade.',
  '让建筑随光流动。': 'Let the building flow with light.',
  '让每个光点呼吸。': 'Let every point of light breathe.',
  '让影像点亮整座城市。': 'Let imagery light up the city.',
  '拖动旋转': 'Drag to rotate', '滚轮缩放': 'Scroll to zoom',
  '视频播放': 'Video playing', '视频已暂停': 'Video paused',
  '动态演示': 'Animated demo', '图片展示': 'Image preview',
  'Chroma 实时交互预览': 'Chroma live interactive preview',
  'Chroma 实时画面': 'Chroma Live',
  '隐藏 Chroma 预览': 'Hide Chroma preview', '显示 Chroma 预览': 'Show Chroma preview',
  '用鼠标交互控制建筑上的粒子画面': 'Use the mouse to control particles on the building',
  '移动鼠标形成漩涡 · 按住吸引 · 右键推散': 'Move to swirl · Hold to pull · Right-click to scatter',
  '切回原素材': 'Return to previous media',
  '使用 Chroma 实时画面': 'Use Chroma Live',
  '将当前粒子效果实时映射到此场景': 'Map the current particle artwork to this scene in real time',
  '将当前粒子效果实时映射到全部三个场景': 'Map the current particle artwork to all three scenes in real time',
  '先在 Chroma Field 制作画面': 'Create an artwork in Chroma Field first',
  '前往 Chroma Field': 'Go to Chroma Field',
  '实时粒子画面': 'Live particle artwork',
  '浮窗交互会实时更新建筑画面': 'Interact in the preview to update the building live',
  'Chroma 实时串流': 'Chroma live stream',
  'Chroma 实时画面已中断，请重新选择。': 'Chroma Live stopped. Select it again to retry.',
  '无法启动 Chroma 实时画面，请检查 WebGL。': 'Chroma Live could not start. Check WebGL support.',
  'Fluid 实时交互预览': 'Fluid live interactive preview',
  'Fluid 实时画面': 'Fluid Live',
  '隐藏 Fluid 预览': 'Hide Fluid preview', '显示 Fluid 预览': 'Show Fluid preview',
  '拖动吸引 · 右键推散': 'Drag to attract · Right-click to repel',
  '正在启动 Fluid 实时画面…': 'Starting Fluid Live…',
  '使用 Fluid 实时画面': 'Use Fluid Live',
  '将流光粒子实时映射到全部三个场景': 'Map Fluid Light particles live to all three scenes',
  'Fluid Live 需要 WebGPU 支持': 'Fluid Live requires WebGPU support',
  'Fluid 实时串流': 'Fluid live stream',
  '无法启动 Fluid 实时画面，请检查 WebGPU 和视频流权限。': 'Fluid Live could not start. Check WebGPU and video stream access.',
};

export function useLightformCopy() {
  const { language } = useLanguage();
  return (chinese: string) => language === 'en' ? english[chinese] ?? chinese : chinese;
}
