import { useLanguage } from '../../language';

const chinese: Record<string, string> = {
  'Upload Image': '上传图片', 'Current': '当前图片', 'Choose an image': '选择图片',
  'History': '历史记录', 'Your images appear here during this session.': '本次访问使用的图片会显示在这里。',
  'Canvas': '画布', 'Settings': '设置', 'Help': '帮助',
  'Move cursor': '移动光标', 'create a vortex': '生成涡旋', 'Hold left': '按住左键',
  'pull particles': '吸引粒子', 'Right click': '单击右键', 'burst outward': '向外爆散',
  'PHOTOGRAPHS': '照片', 'INTO': '化为', 'NEW REALITIES': '全新世界',
  'SAME': '同一张', 'IMAGE': '照片', 'BRIGHTER': '更明亮的', 'WORLDS': '世界',
  'Sampling image pigments…': '正在采样图片色彩…',
  'Drop an image here or click to upload': '将图片拖到这里，或点击上传',
  'Dismiss error': '关闭错误', 'Retry': '重试',
  'Image Palette': '图片色板', 'Extracted from your image': '从图片中提取',
  'Particle Controls': '粒子控制', 'Density': '密度', 'Image Flow': '图像流动',
  'Speed and reach along the image contours. Zero keeps them still.': '沿图像轮廓运动的速度与范围；设为零可停止流动。',
  'Dispersion': '离散度', 'Particle Size': '粒径', 'Visual Mode': '视觉模式',
  'Standard': '标准', 'Fluid': '流体', 'Orbit': '轨道', 'Experimental': '实验',
  'Audio Reactive': '音频响应', 'Audio Source': '音频来源', 'Audio file': '音频文件',
  'Microphone': '麦克风', 'Microphone is live. Sound is not played back.': '麦克风正在输入，声音不会回放。',
  'Sensitivity': '灵敏度', 'Smoothing': '平滑度', 'Bass': '低频',
  'Low Mid': '中低频', 'Mid': '中频', 'High Mid': '中高频', 'Treble': '高频',
  'PNG STILL': 'PNG 静帧', 'Export': '导出',
  'Canvas Settings': '画布设置', 'How to use Chroma Field': 'Chroma Field 使用说明',
  'Close dialog': '关闭对话框', 'Restore default controls': '恢复默认参数',
  'Adjust the live artwork from the panel on the right. Your images stay in this browser session.': '在右侧调整实时画面。图片只保留在本次浏览期间。',
  'Upload a JPG, PNG, or WebP image. Its pigments and edges become a unique, repeatable particle animation.': '上传 JPG、PNG 或 WebP 图片，色彩与边缘会变成可交互的粒子动画。',
  'Move the cursor over the canvas to create a small vortex.': '在画布上移动光标，形成局部涡旋。',
  'Hold the left mouse button for a stronger pull.': '按住鼠标左键，加强吸引力。',
  'Right click to push nearby particles outward. They settle back into the image.': '单击右键推散附近粒子，随后它们会回到原图。',
  'Image Flow changes the speed and reach of contour motion.': '图像流动控制沿轮廓运动的速度与范围。',
  'Choose a song or microphone to make the image respond to sound.': '选择音频文件或麦克风，让图片随声音变化。',
  'Use Export to download the current frame as a PNG.': '点击导出，将当前画面保存为 PNG。',
  'The image could not be processed.': '无法处理这张图片。',
  'Demo image could not be loaded.': '无法加载演示图片。',
  'WebGL is unavailable. Enable hardware acceleration or use a current desktop browser.': '无法使用 WebGL，请启用硬件加速或使用较新的浏览器。',
  'Choose a JPG, PNG, or WebP image.': '请选择 JPG、PNG 或 WebP 图片。',
  'Choose an image under 25 MB.': '请选择小于 25 MB 的图片。',
  'Audio could not be opened.': '无法打开音频。',
  'Microphone could not be started.': '无法启动麦克风。',
  'Microphone input requires HTTPS or localhost and a supported browser.': '麦克风需要 HTTPS 或 localhost，以及支持此功能的浏览器。',
  'Microphone permission was denied.': '麦克风权限被拒绝。',
  'Microphone input could not be started.': '麦克风输入无法启动。',
  'Choose a supported audio file.': '请选择受支持的音频文件。',
  'This image could not be decoded. Try a JPG, PNG, or WebP file.': '无法解码图片，请尝试 JPG、PNG 或 WebP 文件。',
  'Image processing is unavailable in this browser.': '此浏览器无法处理图片。',
  'This image has no visible pixels to turn into particles.': '这张图片没有可生成粒子的可见像素。',
  'The graphics context was lost. Use Retry to restore the canvas.': '图形上下文已丢失，请点击重试恢复画布。',
  'Audio playback could not be started.': '无法播放音频。',
  'PNG export failed.': 'PNG 导出失败。',
  'Pause audio': '暂停音频', 'Play audio': '播放音频',
  'Pause animation': '暂停动画', 'Play animation': '播放动画',
  'Animation timeline': '动画时间轴', 'Reset animation': '重置动画',
  'Toggle fullscreen': '切换全屏', 'Audio reactive': '音频响应',
  'Visual mode': '视觉模式', 'Audio frequency levels': '音频频段',
};

export function useChromaCopy() {
  const { language } = useLanguage();
  return (english: string) => language === 'zh' ? chinese[english] ?? english : english;
}
