import { useLanguage } from '../language';

export const labEnglish: Record<string, string> = {
  '测试项': 'Photo Lab', '用固定视角夜景图片，预演素材与实时粒子的建筑表达。': 'Preview media and live particles on fixed-view architectural night photographs.',
  '色彩粒子场': 'Chroma Field',
  '建筑光影模拟': 'Lightform Studio',
  '正在加载实验…': 'Loading experiment…',
  '上传图片，用色彩与声音塑造可交互的粒子画面。': 'Upload an image and shape interactive particles with color and sound.',
  '在三座建筑场景中预演图片与视频的灯光表达。': 'Preview lighting with images and videos across three architectural scenes.',
  '实验模块': 'Experiments',
  '实验控制台': 'Experiment controls',
  '自定义': 'Custom',
  '昼夜对比位置': 'Day and night comparison position',
  '旋转角度': 'Light angle',
  '光照强度': 'Light intensity',
  '色温': 'Color temperature',
  '场景预设': 'Scene presets',
  '预设效果': 'Effect presets',
  '清晨': 'Dawn',
  '正午': 'Noon',
  '黄昏': 'Dusk',
  '夜间': 'Night',
  '白天': 'Day',
  '夜晚': 'Night',
  '深夜': 'Late night',
  '效果强度': 'Effect strength',
  '动画速度': 'Animation speed',
  '像素颜色': 'Pixel color',
  '空间情绪': 'Lighting moods',
  '自定义光色': 'Custom light color',
  '动态演示': 'Auto preview',
  '播放演示': 'Play demo',
  '暂停演示': 'Pause demo',
  '对比播放': 'Play comparison',
  '关闭说明': 'Close guide',
  '选择左侧实验模块': 'Choose an experiment from the left rail',
  '调整底部参数并观察场景变化': 'Adjust the controls below and observe the scene',
  '拖动昼夜分割线或在场景中移动指针': 'Drag the day/night divider or move the pointer in the scene',
  '概念场景用于交互研究，不代表实际项目。': 'Concept scenes illustrate interactions; they do not depict built projects.',
  '保存当前实验画面': 'Save current scene',
  '实验画面已保存': 'Scene saved',
  '保存失败，请重试': 'Save failed. Please try again.',
  '在画面中拖动指针吸引光粒子；右键推散。可在控制台调整色彩、重力与粘度。': 'Drag to attract light particles; right-click to scatter them. Adjust color, gravity and viscosity below.',
  '光的实验室': 'Light Lab',
  '在这里，你可以亲手探索光与建筑的关系。通过交互实验，直观理解光如何塑造空间、激活立面、营造场景。': 'Explore the relationship between light and architecture. Interactive studies show how light shapes space, animates facades and creates atmosphere.',
  '建筑与光环境背景': 'Architecture and lighting backdrop',
  '日照太阳位置': 'Sun position',
  '实验快捷导航': 'Lab quick navigation',
  '光，': 'Light',
  '让建筑更有生命力。': 'brings architecture to life.',
  '实时光场': 'Light Field',
  '调整光源参数，或移动指针在立面上探索局部光束。': 'Adjust the light source or move the pointer to explore a local beam across the facade.',
  '重置光场参数': 'Reset light field settings',
  '建筑光场静态预览': 'Light field preview',
  '光源类型切换': 'Select light source',
  '太阳光': 'Sunlight',
  '人工光': 'Artificial light',
  '环境光': 'Ambient light',
  '模型切换': 'Switch model',
  '日照时间轴': 'Daylight timeline',
  '拖动调整光源方位': 'Drag to change light direction',
  '功能亮点：': 'Explore the controls:',
  '• 拖动时间轴，模拟日照角度与光影变化': '• Drag the timeline to explore sun angle and shadows',
  '• 调整光源强度、色温、方向': '• Adjust intensity, color temperature and direction',
  '• 支持不同建筑模型（简约模型 / 场馆 / 街区）': '• Switch between simple, venue and district models',
  '• 实时渲染光影与材质反射': '• See light, shadow and material reflections in real time',
  '• 移动指针，观察局部光束如何改变立面明暗': '• Move the pointer to observe how a beam changes the facade',
  '像素立面': 'Pixel Facade',
  '用像素化灯光，探索建筑立面的动态表达。': 'Explore dynamic facade expressions using pixel lighting.',
  '重置像素立面参数': 'Reset pixel facade settings',
  '加载立面模型...': 'Loading facade model…',
  '像素立面需 WebGL 支持': 'Pixel Facade requires WebGL',
  '立面动态效果选择': 'Select facade animation',
  '波浪': 'Wave',
  '涟漪': 'Ripple',
  '流动': 'Flow',
  '图案': 'Pattern',
  '文字': 'Text',
  '晶格': 'Lattice',
  '播放': 'Play',
  '暂停': 'Pause',
  '• 多种动态效果（波浪 / 涟漪 / 流动 / 图案 / 文字）': '• Explore wave, ripple, flow, pattern and text effects',
  '• 调整速度、亮度、颜色': '• Adjust speed, brightness and color',
  '• 支持自定义图案或上传图片': '• Try custom patterns and images',
  '• 实时在建筑立面模型上预览效果': '• Preview effects on the facade model',
  '昼夜切换': 'Day / Night',
  '在时间的流动中，感受建筑在不同时段的气质。': 'See how the building changes character through the day.',
  '• 拖动时间轴查看不同时段的照明效果': '• Drag the timeline to view lighting at different hours',
  '• 对比日景 / 黄昏 / 夜景的氛围': '• Compare day, dusk and night',
  '• 可查看关键时段的灯光策略': '• Review lighting strategies at key moments',
  '• 支持多个建筑案例场景切换': '• Switch between architectural scenes',
  '光色实验室': 'Color Studio',
  '探索不同光色如何改变空间情绪。': 'Explore how the color of light changes the mood of a space.',
  '加载光色空间...': 'Loading color studio…',
  '光色实验需 WebGL 支持': 'Color Studio requires WebGL',
  '选择空间光色预设': 'Choose a lighting preset',
  '暖光 3000K': 'Warm 3000K',
  '中性光 4000K': 'Neutral 4000K',
  '冷白光 6000K': 'Cool white 6000K',
  '彩色光': 'Colored light',
  '温馨 · 沉静 · 亲和': 'Warm · Calm · Welcoming',
  '明朗 · 纯净 · 商务': 'Bright · Clear · Professional',
  '高效 · 现代 · 通透': 'Focused · Modern · Airy',
  '艺术 · 戏剧 · 沉浸': 'Artistic · Dramatic · Immersive',
  '• 调整色温与颜色': '• Adjust color temperature and hue',
  '• 预设不同场景（展厅 / 办公 / 公共空间）': '• Try gallery, office and public-space presets',
  '• 观察空间氛围变化': '• Observe changes in atmosphere',
  '• 支持导出对比图': '• Export a comparison image',
  '流光粒子': 'Fluid Light',
  '基于 WebGPU SPH 动力学与 AI 手势感应，探索建筑交互流光微粒。': 'Explore interactive light particles using WebGPU SPH dynamics and AI hand tracking.',
  '重置流光粒子参数': 'Reset fluid light settings',
  '加载 WebGPU 流光引擎...': 'Loading WebGPU fluid light engine…',
  '流光粒子静态预览': 'Fluid Light preview',
  '• WebGPU GPU Compute 并行计算 3,000+ 流光微粒动力学': '• WebGPU compute simulates more than 3,000 light particles in parallel',
  '• 鼠标光标漫游向心吸附，右键释放推散光浪': '• Attract particles with the pointer; right-click to scatter them',
  '• MediaPipe AI 隔空手势感知：食指导引流光、捏合手势推散冲击波': '• MediaPipe hand tracking: guide with a finger or pinch to scatter particles',
  '• 4 组建筑级色温调色板（暖金 3000K / 极光冷白 6000K / 双色温 / 日光白）': '• Four architectural palettes: warm gold, cool white, dual temperature and daylight',
  '使用指引': 'How to use the lab',
  '✓ 实验画面已截取保存！': '✓ Lab image saved!',
  '1 选择模式': '1 Choose a mode',
  '选择一个实验模块': 'Choose an experiment',
  '2 调整参数': '2 Adjust settings',
  '通过鼠标或触控调整光源 / 效果': 'Use mouse or touch to adjust light and effects',
  '3 观察变化': '3 Observe changes',
  '实时查看建筑的光影与氛围': 'Watch light, shadow and atmosphere change',
  '点击截取保存当前画面': 'Click to save the current image',
  '4 保存分享': '4 Save and share',
  '截取画面，分享你的光影实验': 'Capture and share your lighting study',
  '浏览精选作品工程档案': 'Browse selected project files',
  '清晨自然采光': 'Early morning daylight',
  '利用晨光与天窗深邃开洞，自然漫射光渗透室内。': 'Morning light enters through deep skylight openings and diffuses through the interior.',
  '正午顶光抑制': 'Midday glare control',
  '强日照时段，百叶与深挑檐阻断直射眩光。': 'Louvers and deep overhangs block direct glare in strong sunlight.',
  '黄昏泛光初启': 'Dusk lighting begins',
  '室内透光渐显，建筑内外明暗交界形成柔和层次。': 'Interior light becomes visible and softens the boundary between inside and outside.',
  '夜景重点照明': 'Nighttime accents',
  '泛光与立面轮廓全开，倒影与天际线产生戏剧性对话。': 'Floodlighting and facade outlines engage with reflections and the skyline.',
  '深夜节能模式': 'Late-night energy saving',
  '关闭高功率立面泛光，保留安全导向与轮廓呼吸微光。': 'High-power floodlighting switches off while wayfinding and a subtle outline remain.',
  '世纪广场白天自然采光': 'Century Square in daylight',
  '世纪广场夜景人工照明': 'Century Square at night',
  '拖动对比日景与夜景': 'Drag to compare day and night',
  '拖动滑块对比昼夜照明': 'Drag slider to compare day and night lighting',
  '昼夜时间轴': 'Day and night timeline',
  '日景': 'Day',
  '暖色场景': 'Warm scene',
  '夜景': 'Night',
  '照明状态': 'Lighting states',
  '重置': 'Reset',
  '原始场景图片 · 2018 年项目 / 2023 年画册。离散状态切换，不代表连续照明模拟。': 'Original scene images · 2018 project / 2023 portfolio. Discrete states; this is not a continuous lighting simulation.',
  '流光粒子需 WebGPU 支持': 'Fluid Light requires WebGPU',
  '您的浏览器或当前显卡环境暂不支持 WebGPU Compute Shader。': 'Your browser or graphics environment does not support WebGPU Compute Shader.',
  '推荐使用最新版本 Chrome 113+ 或 Edge 浏览器开启硬件加速进行体验。': 'Try an up-to-date Chrome or Edge browser with hardware acceleration enabled.',
  '流光交互工具栏': 'Fluid Light controls',
  '切换为 AI 手势感应模式': 'Switch to AI hand tracking',
  '切换为鼠标光标模式': 'Switch to mouse pointer',
  '手势': 'Gesture',
  '光标': 'Pointer',
  '继续模拟': 'Resume simulation',
  '暂停模拟': 'Pause simulation',
  '推散光浪 (Pinch)': 'Scatter particles (pinch)',
  '食指导光': 'Guide light with finger',
  '手势追踪预览窗': 'Hand tracking preview',
  'AI 手势感知': 'AI hand tracking',
  '最小化画中画': 'Minimize preview',
  '正在连接摄像头...': 'Connecting to camera…',
  '请将右手置于镜头前': 'Place your right hand in front of the camera',
  '食指导光中 · 移动手掌': 'Move your hand to guide the light',
  '捏合中 · 释放流光冲击波': 'Pinch to scatter light particles',
  '摄像头连接受限': 'Camera access unavailable',
  '无法获取摄像头权限或加载手势识别模型': 'Unable to access the camera or load the hand tracking model',
  '重力场': 'Gravity',
  '调节环境重力加速度': 'Adjust gravity',
  '流体粘度': 'Viscosity',
  '调节光微粒流动的粘滞阻力': 'Adjust particle flow resistance',
  '光粒子尺度': 'Particle size',
  '调节光斑微内核渲染半径': 'Adjust particle rendering radius',
  '微粒': 'particles',
  '3,000+ 微粒': '3,000+ particles',
  '自定义渐变': 'Custom gradient',
  '低速颜色': 'Low-speed color',
  '高速颜色': 'High-speed color',
  '颜色随运动速度过渡': 'Colors blend with particle speed',
  '粒子数量': 'Particle count'
};

export function useLabCopy() {
  const { language } = useLanguage();
  return (chinese: string) => language === 'en' ? labEnglish[chinese] || chinese : chinese;
}
